### ISSUE TITLE
Manual Installation of geocoder

### ISSUE THREAD

**Issue by Helen-Jiahuan-H** [degauss-org/geocoder#52] opened 2023-10-31 01:26 UTC
Hello,

I was trying to install geocoder manually by following the instruction here (https://degauss.org/manual_install.html). I followed the section on "Installation on CentOS 7" and encountered an issue at the very last step, which is shown in the screenshot below.
<img width="941" alt="Screen Shot 2023-10-30 at 9 21 14 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/08dbbc81-6a4e-41a0-afa2-547f5a1c5931">

After I typed "git clone https://github.com/cole-brokamp/geocoder", it asked User name and password for the GitHub.com (please see the screenshot below). I tried my user name, but when I tried to type in password, no character could be entered.
<img width="624" alt="Screen Shot 2023-10-30 at 9 23 40 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/0295f9b5-dc26-4335-b2d4-efd1cbbd28ee">

I have tried to figure out the reason for the problem on my own by looking at the repo "https://github.com/cole-brokamp/geocoder", but it seems it does not exist. I wonder is it because I don't have access to it? 

Any help on this issue will be very much appreciated. Thank you very much in advance!

Best,
Helen

**Comment by cole-brokamp** [comment] 2023-10-31 12:55
duplicate of #51 ?

**Comment by cole-brokamp** [comment] 2023-10-31 12:57
On a quick read, passwords characters should not show when typing, this is for security reasons.  It is still reading the password.  Regardless, git authentication shouldn't be necessary for this install.  You can replace the repo with https://github.com/degauss-org/geocoder -- it has been moved.

**Comment by Helen-Jiahuan-H** [comment] 2023-10-31 16:30
> On a quick read, passwords characters should not show when typing, this is for security reasons. It is still reading the password. Regardless, git authentication shouldn't be necessary for this install. You can replace the repo with https://github.com/degauss-org/geocoder -- it has been moved.

Hi Dr. Brokamp,

Thank you very much for your reply! It is regarding the same manual installation as #51, but the problem is a bit different, so I created another issue. Sorry if this created any inconvenience! I have tried the process replacing "https://github.com/cole-brokamp/geocoder" with "https://github.com/degauss-org/geocoder", but I still have some problems for the installation process.
I replaced the command "sudo make install" with "sudo make -f Makefile.ruby install", and it seems to be working despite some ERROR in the output. But after running "sudo gem install Geocoder-US-2.0.4.gem", I got "ERROR: Could not find a valid gem 'Geocoder-US-2.0.4.gem' (>= 0) in any repository" (please see the screenshot below). Are you aware of any updates for the 'Geocoder-US-2.0.4.gem' or any approaches to solve this problem? 
<img width="644" alt="Screen Shot 2023-10-31 at 12 25 29 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/971b3eec-42e6-4794-87af-44d633672f40">

Thank you very much!

Best,
Helen

**Comment by cole-brokamp** [comment] 2023-10-31 16:41
Thanks for the detailed followup.  I'm honestly unfamiliar with Ruby in general.  I know enough to get the geocoder Dockerfile to run ¯\_(ツ)_/¯ 

Is that different than what is working in the Dockerfile here? https://github.com/degauss-org/geocoder/blob/master/Dockerfile

Also -- may I ask why you are preferring the manual installation instead of the docker installation?

**Comment by Helen-Jiahuan-H** [comment] 2023-10-31 16:49
> Thanks for the detailed followup. I'm honestly unfamiliar with Ruby in general. I know enough to get the geocoder Dockerfile to run ¯_(ツ)_/¯
> 
> Is that different than what is working in the Dockerfile here? https://github.com/degauss-org/geocoder/blob/master/Dockerfile
> 
> Also -- may I ask why you are preferring the manual installation instead of the docker installation?

Hi Dr. Brokamp,

Thank you for providing the information about the Dockerfile! May I ask how I can use this Dockerfile to install the geocoder? Or is it relied on the Docker Desktop?

I'm trying manual installation because I would like to use the degauss geocoder function, degauss_run(addresses, "geocoder", "3.2.1", quiet = FALSE), in a R studio on a virtual machine, where I'm not allowed to install Docker Desktop. Do you have any insights on how I could use the degauss_run(addresses, "geocoder", "3.2.1", quiet = FALSE) function on a virtual machine without installing Docker Desktop? Thank you very much!

Best,
Helen

**Closed** 2023-10-31 20:07 UTC
